### PR TITLE
remove redundant props from PickerIOS

### PR DESCRIPTION
**Pull request by ecreeth**
# Summary
These properties has been removed from React Native Core.

1. onResponderTerminationRequest
2. onStartShouldSetResponder

**Original Summary:** PR commited in [f580409](https://github.com/facebook/react-native/commit/9cefc96e43d2b9326b88c6aa19c3db2c58013ddf)  Props are being ignored on native side, let's get rid of them. by @sammy-SC 

These properties are also not reflected in the official documentation

### CODE REVIEW

**Comment by chakrihacker** [comment]
@ecreeth can you update your PR??

**Comment by ecreeth** [comment]
Done!

**Comment by chakrihacker** [comment]
I will merge it by tomorrow

**Comment by chakrihacker** [comment]
@ecreeth Thanks for the PR 🙏

**Comment by dozoisch** [comment]
FYI for anyone on react-native 0.61, this change seems to be breaking and those props are required for proper behavior on iOS. Otherwise, the picker doesn't accept changes if the touch position if over the picker.

**Pull request merged**
