### PR TITLE
migrate-to-androidx

### LINKED ISSUE #36: AndroidX support
currently I had to apply [this hack](https://itnext.io/react-native-how-to-handle-an-app-with-both-pre-androidx-and-androidx-dependencies-rn60-bf4df7ea0dd2) to get the package to work. As androidx is now standard for react native, this package should support it as well.

### PR DESCRIPTION
**Pull request by chakrihacker**
closes #36

### CODE REVIEW

**Comment by chakrihacker** [comment]
Thanks @sharma0611 for testing it. Merging PR 👍

**Comment by FRizzonelli** [comment]
Can you make a new release to npm? Otherwise I need to install it from master branch :(

**Comment by chakrihacker** [comment]
yes will do

**Comment by chakrihacker** [comment]
@satya164 , @grabbou Can you provide npm access. I want to publish new version

**Comment by satya164** [comment]
cc @Titozzz

**Comment by jainkuniya** [comment]
Released `1.2.0`

**Comment by jainkuniya** [comment]
Thanks @chakrihacker for taking this up.
Release is automatic and managed by [semantic-release-bot](https://semantic-release.gitbook.io/semantic-release/). So basically anything goes to master, can directly be published.

**Comment by FRizzonelli** [comment]
Thanks for the fast response guys @satya164 @chakrihacker @jainkuniya <3

**Pull request merged**
