### PR TITLE
fix: rename RCT to RNC to avoid naming conflict from one in RNCore

### LINKED ISSUE #21: Duplicate Symbols after upgrade to Xcode 11 / react-native 0.60.5
# Bug

Receiving the following build error when I try to build my project, now. I updated react-native-picker and react-native and am using XCode 11/ios 13. I have tried to remove the build library linking in XCode, but it keeps getting generated after I run, and I get the same error. Here ist he error: 

```
duplicate symbol '_OBJC_IVAR_$_RCTPicker._selectedIndex' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
duplicate symbol '_OBJC_IVAR_$_RCTPicker._font' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
duplicate symbol '_OBJC_IVAR_$_RCTPicker._items' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
duplicate symbol '_OBJC_IVAR_$_RCTPicker._color' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
duplicate symbol '_OBJC_CLASS_$_RCTPicker' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
duplicate symbol '_OBJC_METACLASS_$_RCTPicker' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
duplicate symbol '_OBJC_IVAR_$_RCTPicker._textAlign' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
duplicate symbol '_OBJC_IVAR_$_RCTPicker._onChange' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
duplicate symbol '_OBJC_CLASS_$_RCTPickerManager' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPickerManager.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPickerManager.o)
duplicate symbol '_OBJC_METACLASS_$_RCTPickerManager' in:
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPickerManager.o)
    /Users/shawnadonnelly/Documents/GitHub/RN-PartnerPay/ios/build/PartnerPay/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPickerManager.o)
ld: 10 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 35.44 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 26, 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 1.1.1

## Steps To Reproduce
react-native run-ios --simulator "iPhone 11 Pro";

1.
2.
...

Describe what you expected to happen:

1. Build
2.

### PR DESCRIPTION
**Pull request by kyo504**
# Summary
Basically, this PR fixes #21 so I changed the prefix from RCT to RNC to be consistent with naming convention of other RNC libraries and to avoid naming naming conflict betweenbetween RNCore and RNCPicker. Also this includes some clean up.

## Test Plan

1. RN(0.61.2) + RNCPicker by autolinking - OK
2. RN(0.59.1) + RNCPicker by manual linking - OK 

### What's required for testing (prerequisites)?
N/A

### What are the steps to reproduce (after prerequisites)?
1. Create template project with 0.61.x
2. Install package and pod dependency
3. Build iOS application

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [n/a] I added the documentation in `README.md`
- [n/a] I mentioned this change in `CHANGELOG.md`
- [n/a] I updated the typed files (TS and Flow)
- [n/a] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by chakrihacker** [comment]
Hello @kyo504 thanks for the PR, example app is not working, can you please check it.

**Comment by chakrihacker** [comment]
@jainkuniya do you mind, If I review this PR??

**Comment by jainkuniya** [comment]
@chakrihacker sure, it will be a great help.

**Comment by kyo504** [comment]
@chakrihacker Sorry about it(I had tested with sample project with examples). The reason why example app is not working is due to native dependency. I have linked RNCPicker to main iOS project. Now it works fine(tested with example example app). Could you check?

**Comment by chakrihacker** [comment]
@kyo504 example is working perfectly fine, merging now

**Pull request merged**
