### PR TITLE
fix: Fix Imports for MacOS Support

### PR DESCRIPTION
**Pull request by bralax**
# Summary
A little while ago I submitted a pull request for macOS support for this library. I realized recently in using the version I submitted, that I forgot an important import in RNCPicker.h. This pull request tries to fix that.

## Test Plan
It now no longer fails to compile

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ❌     |
| MacOS     |    ✅     |
## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Inadvertently made #144 before I realized you already had this open. Would be great to get this merged!

**Review by Saadnajmi — APPROVED** [review]

**Review by Naturalclar — APPROVED** [review]
@bralax Thank you!

**Comment by ospfranco** [comment]
Sorry to get involved here, but I'm trying to use the latest release and it fails to compile, check out https://github.com/react-native-picker/picker/issues/185

**Pull request merged**
